### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by left0ver** [yesmore/cv-mkr#14]
![XU)VS_F RN7IV2{E`Q(D~$T](https://user-images.githubusercontent.com/89240290/164885808-c3045e5b-e811-43d5-8979-15ecfbd4fa84.png)
出现好几次这样的问题，应该是窗口缩放导致的

**Comment by yesmore** [comment]
这个内容布局不是响应式的，在**发布版**长宽高都是固定的，也就是窗口是不可拉伸的；但是在**开发**时可调整大小，每次改变窗口大小后，手动刷新一下应用即可适配；
具体代码可参考 [main/electron.ts](https://github.com/yesmore/cv-mkr/blob/master/app/main/electron.ts) 创建主窗口代码中的  **resizable** 属性设置。
